#!/bin/bash

set -o errexit
if [ "$1" == "core" ]; then
    rm -rf "../core/docs"
elif [ "$1" == "user" ]; then
    rm -rf "../user/docs"
elif [ "$1" == "tpp" ]; then
    rm -rf "../tpp/docs"
elif [ "$1" == "sdk" ]; then
    rm -rf "../sdk/docs"
fi

# rm -rf html
cp Doxyfile Doxyfile_temp

if [ "$1" == "core" ]; then
    echo "INPUT = ../core/src /n  ../../README.md" >> Doxyfile
    echo "PROJECT_NAME = \".Net Core\" " >> Doxyfile
    echo "OUTPUT_DIRECTORY  = ../core/docs" >> Doxyfile
elif [ "$1" == "user" ]; then
    echo "INPUT = ../user/src /n  ../../README.md" >> Doxyfile
    echo "PROJECT_NAME = \".Net User\" " >> Doxyfile
    echo "OUTPUT_DIRECTORY  = ../user/docs" >> Doxyfile
elif [ "$1" == "tpp" ]; then
    echo "INPUT = ../tpp/src /n  ../../README.md" >> Doxyfile
    echo "PROJECT_NAME = \".Net Tpp\" " >> Doxyfile
    echo "OUTPUT_DIRECTORY  = ../tpp/docs" >> Doxyfile
elif [ "$1" == "sdk" ]; then
    echo "INPUT = ../sdk/src /n  ../../README.md" >> Doxyfile
    echo "PROJECT_NAME = \".Net SDK\" " >> Doxyfile
    echo "OUTPUT_DIRECTORY  = ../sdk/docs" >> Doxyfile
fi

doxygen Doxyfile

cp Doxyfile_temp Doxyfile
rm -rf Doxyfile_temp

if [ "$1" == "core" ]; then
    python refactor_docs.py "../core/docs"
elif [ "$1" == "user" ]; then
    python refactor_docs.py "../user/docs"
elif [ "$1" == "tpp" ]; then
    python refactor_docs.py "../tpp/docs"
elif [ "$1" == "sdk" ]; then
    python refactor_docs.py "../sdk/docs"
fi
#python refactor_docs.py